### ISSUE TITLE
New Layout/Template

### ISSUE THREAD

**Issue by ChuckSRQ** [ethereumproject/TokenMint#14]
I think the site would look better with this layout. 

[Horizontal Admin Free Website Template - Free-CSS.com.zip](https://github.com/ethereumproject/TokenMint/files/1065492/Horizontal.Admin.Free.Website.Template.-.Free-CSS.com.zip)

**Comment by splix** [comment]
Where it came from? what is the license of this files?

**Comment by elaineo** [comment]
judging from the source code in the included files:

`/*=============================================================
    Authour URI: www.binarytheme.com
    License: Commons Attribution 3.0

    http://creativecommons.org/licenses/by/3.0/

    100% Free To use For Personal And Commercial Use.
    IN EXCHANGE JUST GIVE US CREDITS AND TELL YOUR FRIENDS ABOUT US
   
    ========================================================  */`

**Comment by splix** [comment]
great :) asked because most of theme sites doesn't allow to redistribute
