### ISSUE TITLE
Alfa Release 

### ISSUE THREAD

**Issue by elaineo** [ethereumproject/TokenMint#42]
Basic Requirements should be complete, one last pass-through to make sure nothing is too wrong.

- [x] Make sure there is nothing that sounds illegal (no references to scams, ponzis, etc)
- [x] Check for broken links 
- [x] Flow is logical and complete (create token -> launch crowdsale -> view crowdsale)
- [x] Looks reasonable on desktop and mobile
- [ ] Home page "Events" -- replace with real coins?
- [x] JSON file import has no unlock button
- [x] Clarify what it means to open a wallet

Any other comments?

**Comment by realcodywburns** [comment]
I cant unlock wallet from json using chrome on windows. No unlock button.

**Comment by elaineo** [comment]
Except for the "events" box, i think we've covered all the alfa components. closing this out!
