### ISSUE TITLE
Have option to NOT do an ICO

### ISSUE THREAD

**Issue by ChuckSRQ** [ethereumproject/TokenMint#45]
I think a lot of users would like to just create their own token and not have to do an ICO. They just want to be able to play with them and use them for whatever reason.

**Comment by elaineo** [comment]
if you "Mint a Token" without continuing to "Launchan ICO", that's exactly what that does. We should make that more clear.

**Comment by ChuckSRQ** [comment]
Yes. It should show something like...

Tokens Created!

You can now find your tokens at your address. 
With the Contract Address: Hex Address

Instructions for how to View/Send your tokens can be found here. 
https://www.myetherwallet.com/#help (Section 7)

**Comment by elaineo** [comment]
okay, i will add this to the "Need better feedback" #43

**Comment by elaineo** [comment]
added a modal, will be addressed further in #52
