### ISSUE TITLE
CAP on Crowdsale Fundraising

### ISSUE THREAD

**Issue by ChuckSRQ** [ethereumproject/TokenMint#56]
I would suggest a CAP of 100k USD.

**Comment by elaineo** [comment]
Have the cap as an option on launching an ICO? We can't enforce a USD cap, because the price of ETC fluctuates. ETC cap is an option though.

**Comment by ChuckSRQ** [comment]
Well would it be possible to use the exchange rate from say Coin Market Cap and use their API? 

https://www.cryptocompare.com/api/#-api-data-price-

**Comment by elaineo** [comment]
a smart contract can't access that data, we'd need to set up a price oracle.

**Comment by ChuckSRQ** [comment]
How about 2,500 ETC then? That's around 50k currently.  Just to be safe.
