### ISSUE TITLE
Price per Token (in ether) >= 1?

### ISSUE THREAD

**Issue by mrsinguyen** [ethereumproject/TokenMint#66]
allow:

<img width="1182" alt="screen shot 2017-06-30 at 2 42 33 pm" src="https://user-images.githubusercontent.com/96544/27725855-660237c2-5da2-11e7-89b7-d7525b956c7f.png">

not allow:

<img width="1203" alt="screen shot 2017-06-30 at 2 42 21 pm" src="https://user-images.githubusercontent.com/96544/27725862-6cdbe61a-5da2-11e7-9062-d88a77ba9dd4.png">

**Comment by elaineo** [comment]
Fixed: https://github.com/ethereumproject/TokenMint/commit/e3393ccf90a695d3edc45f0b5810db48341df8b0
