### ISSUE TITLE
testnet or real environment

### ISSUE THREAD

**Issue by senzacionale** [ethereumproject/TokenMint#72]
Where can I choose testnet (ropsten) or live environment. Because I do not want to test on real environment.

Thx

**Comment by elaineo** [comment]
You will have to run your own testnet node, but you can edit it in the rpc file: https://github.com/ethereumproject/TokenMint/blob/master/src/lib/rpc.js

**Comment by senzacionale** [comment]
@elaineo can you provide an example for rpc.js? I can not make it to work with ropsten. 

Thank you
