### ISSUE TITLE
Private key length is invalid

### ISSUE THREAD

**Issue by kimisan** [ethereumproject/TokenMint#78]
I use the private key file,
But i got this, any recommendation ?
" Unhandled Rejection (RangeError): private key length is invalid "

----------
With Ethereum Classic Geth 3.5.86

**Comment by elaineo** [comment]
@kimisan are there any spaces at the end of the key? 

Good point though, the UI should remove blank spaces

**Comment by kimisan** [comment]
Maybe no.
After npm start, 
I use the file mode, it mean i use JSON or Keystore File.
And 
1. it will show the password enter field
2. enter the pass
3. press the open wallet button
4. The browser show the "" Unhandled Rejection (RangeError): private key length is invalid ""

By the way, what is your development environment ?

**Comment by elaineo** [comment]
i'm using node v6.11.1, npm 3.10.10

So far I cannot reproduce this. How did you generate the JSON file? Can you generate a fresh account at http://myetherwallet.com and see if it still happens?

**Comment by kimisan** [comment]
oh i see it.
I directly use the JSON file from keystore...
ok,
I will use myetherwallet.com  , and try it again.
Thanks

**Comment by elaineo** [comment]
@kimisan is this still broken?

**Comment by kimisan** [comment]
@elaineo Sorry, I visit Japan this week,
I will check your recommendation tomorrow. ^^

**Comment by kimisan** [comment]
@elaineo i have use the myetherwallet.com solution , i think it work.
But I want to send some token to other wallet address
Do you know how to check the balance of other wallet address ?
Thank you

**Comment by elaineo** [comment]
i will add an option where you can just enter the wallet address to view
balance :)

On Sat, Sep 9, 2017 at 10:00 AM, Kimi Sian-Yu Chen <notifications@github.com

**Comment by kimisan** [comment]
Great, I think it issue (Private key length is invalid) can close now 
Thank you

**Comment by elaineo** [comment]
But it is still a bug where you cannot load a geth keystore file, right?

**Comment by kimisan** [comment]
@elaineo 
Now i know the reason why the key length is invalid.
I have to enter the  key length from ETC Geth client, it can enter much shorter password .
And myetherwallet.com can not let you enter the much shorter password.
I think it is why Private key length is invalid.

**Comment by elaineo** [comment]
ohh okay thank you!
