### ISSUE TITLE
Test with testner, Ropsten for example

### ISSUE THREAD

**Issue by senzacionale** [ethereumproject/TokenMint#88]
https://github.com/ethereumproject/TokenMint/blob/master/src/lib/rpc.js

@elaineo can you provide an example for rpc.js? I can not make it to work with ropsten.

Thank you

**Comment by elaineo** [comment]
You should change this line:
`const NodeApi = "https://mewapi.epool.io";`

Replace `mewapi.epool.io` with your ropsten API.

**Comment by elaineo** [comment]
(btw, i tested with `https://ropsten.infura.io`... see if that works.)

**Comment by senzacionale** [comment]
@elaineo thank you, that was fast response :)

I will test it right now

**Comment by senzacionale** [comment]
I tested but I got always this error:

> Unhandled Rejection (BigNumber Error): new BigNumber() not a number: 

You can test it with this private key from ropsten network:
dcc7f7b0eeb1c3b70038033333adcfd5a0a49324215ec7c824cee819d448304d

I also open new ticket regarding to this topic

**Comment by elaineo** [comment]
Where does that error appear?

**Comment by senzacionale** [comment]
For example when I click on "Mint a Token" -> "Select the format of your private key." -> click "Open Wallet"

**Comment by senzacionale** [comment]
@elaineo can you reproduce error?

Thank you

**Comment by elaineo** [comment]
I'm out of the country right now, I will be back at my computer on Friday
and will try again then.

**Comment by senzacionale** [comment]
ok thank you

**Comment by elaineo** [comment]
Okay sorry, some of the contracts had not been updated and deployed on testnet. It should work now on this branch: https://github.com/ethereumproject/TokenMint/tree/ropsten

**Comment by senzacionale** [comment]
thank you. I will test it and let you know.

**Comment by senzacionale** [comment]
thank you. I will test it and let you know.

small update

I checked the code

do I need this?

-export const IcoMachineAddress = "0xbebd7b2a9edb51b28854236041daec1f5e0f2398";
+export const IcoMachineAddress = "0xD459e10654a2387Fc6ab2040627febEbEa682C56";

-export const RegistryAddress = '0xf4d139fE4f73725dcc6eb364e4593a00F07DC0a9';
+export const RegistryAddress = '0x20ea4049c154769264d8667d780ae9647c150f21';

**Comment by elaineo** [comment]
yes, you need the second set (contract addresses are different on ropsten)

**Comment by senzacionale** [comment]
what is the difference between IcoMachineAddress and RegistryAddress ? And why to hardcode it

**Comment by elaineo** [comment]
Registry: https://github.com/ethereumproject/TokenMint/blob/master/contracts/deployed/manReg.sol

IcoMachine: https://github.com/ethereumproject/TokenMint/blob/master/contracts/deployed/icoMachine.sol

hardcoded because they are deployed contracts.

**Comment by elaineo** [comment]
there is an open issue to put the addresses into  a config file: https://github.com/ethereumproject/TokenMint/issues/73

**Comment by senzacionale** [comment]
ok, If I want to redeploy it on different address then I simply need to change hard coded values. Does not hurt me so much currently. Thx
