### ISSUE TITLE
unlock account to continue

### ISSUE THREAD

**Issue by senzacionale** [ethereumproject/TokenMint#89]
I want to unlock my account with UTC JSON Keystore File from Ethereum Wallet like is written here
https://theethereum.wiki/w/index.php/Accounts,_Addresses,_Public_And_Private_Keys,_And_Tokens

or with simple private key (you can use it for test): dcc7f7b0eeb1c3b70038033333adcfd5a0a49324215ec7c824cee819d448304d

but I always get this error:

`Unhandled Rejection (BigNumber Error): new BigNumber() not a number: 
raise
D:\TokenMint\node_modules\bignumber.js\bignumber.js:1190
  1187 | 
  1188 |        // Throw a BigNumber Error.
  1189 |        function raise( caller, msg, val ) {
> 1190 |            var error = new Error( [
  1191 |                'new BigNumber',     // 0
  1192 |                'cmp',               // 1
  1193 |                'config',            // 2
View compiled
(anonymous function)
D:\ICO\TokenMint\node_modules\bignumber.js\bignumber.js:1178
  1175 | 
  1176 |                    // 'new BigNumber() not a number: {n}'
  1177 |                    // 'new BigNumber() not a base {b} number: {n}'
> 1178 |                    if (ERRORS) raise( id, 'not a' + ( b ? ' base ' + b : '' ) + ' number', str );
  1179 |                    x.s = null;
  1180 |                }
  1181 | 
View compiled
new BigNumber
D:\ICO\TokenMint\node_modules\bignumber.js\bignumber.js:193
  190 | 
  191 |                    str = n + '';
  192 |                } else {
> 193 |                    if ( !isNumeric.test( str = n + '' ) ) return parseNumeric( x, str, num );
  194 |                    x.s = str.charCodeAt(0) === 45 ? ( str = str.slice(1), -1 ) : 1;
  195 |                }
  196 |            } else {
View compiled
hexToDecimal
D:\ICO\TokenMint\src\lib\convert.js:31
  28 | }
  29 | 
  30 | export function hexToDecimal(hex) {
> 31 |     return new BigNumber(sanitizeHex(hex)).toString();
  32 | }
  33 | 
  34 | export function contractOutToArray(hex) {
View compiled
(anonymous function)
D:\ICO\TokenMint\src\store\tokenActions.js:26
  23 |     to: IcoMachineAddress,
  24 |     data: data,
  25 | }, "latest"]).then((result) => {
> 26 |     const idx = hexToDecimal(result);
  27 |     for (let i=0; i<idx; i++) {
  28 |         dispatch(fetchOwnToken(address, i))
  29 |     }
View compiled`

**Comment by elaineo** [comment]
was this on testnet?

**Comment by senzacionale** [comment]
yes this was on testnet

**Comment by elaineo** [comment]
ok cool, it should be fixed on the ropsten branch now.

**Comment by senzacionale** [comment]
thank you. I think you can close this bug as is then duplicated
