### ISSUE TITLE
Read spreadsheet for Bounty program

### ISSUE THREAD

**Issue by ansajjasna** [ethereumproject/TokenMint#90]
Hi, is it possible to read spreadsheet for bounty program and send tokens back to specific address?
Is it possible to use oraclize and call some API outside from your project?

Thank you

**Comment by elaineo** [comment]
I don't understand the question. Can you provide an example?

**Comment by ansajjasna** [comment]
Hi, sure I will explain it little better

1. We have some excel (spreadsheet) file with different ETH addresses inside. Is it somehow possible to parse this excel with TokenMint and send new ERC-20 tokens back to this address?

2. Nowadays is very popular to allow only confirmed people to participate in crowdsale. So people which confirm email for example. Is it possible from TokenMint to call API outside and check if email is confirmed. And if is confirmed transaction will be allowed.

**Comment by elaineo** [comment]
Right now that is not supported. That can be added as a future feature, however.

**Comment by ansajjasna** [comment]
ok thank you for this information. Can you tell me what are you using for communication between UI and block chain and maybe I can help with implementation.

**Comment by elaineo** [comment]
RPC connector here: https://github.com/ethereumproject/TokenMint/blob/master/src/lib/rpc.js

**Comment by ansajjasna** [comment]
Can you try to describe solution idea how you will do it? And then I can start, because it is your project.

**Comment by elaineo** [comment]
i don't know the best way to do it, i will have to think about it. it would be easier if you try to familiarize yourself with the code base and propose how you want to solve it.

**Comment by ansajjasna** [comment]
@elaineo last question. If I want to call method and save something in solidity for example this event

event Whitelisted(address addr, bool status);

how can I do this with rpc.js? What i need to do to call this Whitelisted(address addr, bool status);

**Comment by elaineo** [comment]
you will need to create a new smart contract with the Whitelisted function. this is unrelated to rpc.js.

For testing smart contracts, I recommend Truffle (https://github.com/trufflesuite/truffle) or browser solidity (https://ethereum.github.io/browser-solidity/)

**Comment by senzacionale** [comment]
@elaineo sure I understand that I need new smart contract. I know solidity but my problem is how to do a communication between rpc.js and solidity event. So if I add new event in smart contract how can I do a communication between UI and this event.

I want to call this event from your UI and add address to it

`event Whitelisted(address addr, bool status);`

**Comment by ansajjasna** [comment]
@elaineo sure I understand that I need new smart contract. I know solidity but my problem is how to do a communication between rpc.js and solidity event. So if I add new event in smart contract how can I do a communication between UI and this event.

I want to call this event from your UI and add address to it

event Whitelisted(address addr, bool status);

**Comment by elaineo** [comment]
@ansajjasna you would need to create a filter (https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_newfilter)

i don't like using event filters though, they tend to be slow.
