### ISSUE TITLE
Programming language for UI

### ISSUE THREAD

**Issue by senzacionale** [ethereumproject/TokenMint#91]
Which programming language did you use for UI. It is not web3.js and I would like to know which one is used that I can read docs.

**Comment by elaineo** [comment]
ummm... Javascript/ReactJS

**Comment by senzacionale** [comment]
ReactJS for smart contract communication also?

**Comment by elaineo** [comment]
ReactJS is a javascript framework. web3 is a javascript API for the JSONRPC. I guess what you are trying to ask is how the the JSONRPC API works? the documentation is here: https://github.com/ethereum/wiki/wiki/JSON-RPC
