### ISSUE TITLE
tokenmint is inaccessible via https

### ISSUE THREAD

**Issue by shanejonas** [ethereumproject/TokenMint#93]
![image](https://user-images.githubusercontent.com/364566/32194123-af6a8980-bd76-11e7-9252-dcee2c8650a7.png)

its using the github cert

**Comment by elaineo** [comment]
hmm, i think this is the only way to use SSL with a custom domain. correct me if i'm wrong.
https://hackernoon.com/set-up-ssl-on-github-pages-with-custom-domains-for-free-a576bdf51bc

**Comment by elaineo** [comment]
okay, all set!
